export * from "./Banner";
export * from "./Before";
export * from "./Benefits";
export * from "./Comparison";
export * from "./Difference";
export * from "./Gallery";
export * from "./MainSwiper";
export * from "./PartnersList";
export * from "./ParallaxBeforeFooter";
