import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "@/app/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className={
            "flex flex-col items-center min-h-dvh w-full h-max relative"
          }
        >
          <Header />

          <main
            className={
              "flex justify-center flex-grow py-20 w-full overflow-x-hidden"
            }
          >
            <div className={"max-w-limitation w-full"}>{children}</div>
          </main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
